# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [3]:
pip list | grep 'numpy'

Note: you may need to restart the kernel to use updated packages.
'grep' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.


#### Q3 : Créer un vecteur nul de taille 10

In [4]:
empty = np.zeros(10)
empty

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [5]:
empty[3] = 1
empty

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [6]:
z = np.arange(10,51)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [7]:
np.flip(z)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [8]:
np.random.randint(8, size=(3,3))

array([[1, 0, 5],
       [5, 4, 7],
       [6, 4, 7]])

#### Q8 : Créer une matrice identié 3x3 

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [10]:
np.random.rand(3,3,3)

array([[[0.70425483, 0.17951594, 0.59696036],
        [0.8814338 , 0.8212076 , 0.46304501],
        [0.26109113, 0.5952985 , 0.4326843 ]],

       [[0.98780543, 0.49800809, 0.86216573],
        [0.07321721, 0.02299682, 0.38124325],
        [0.58948331, 0.3627428 , 0.14668969]],

       [[0.64056182, 0.14603897, 0.44013684],
        [0.66078526, 0.91746179, 0.50754649],
        [0.66807879, 0.59749599, 0.15634359]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [11]:
z = np.random.rand(10,10)
np.amin(z)

0.004824292087451165

In [12]:
np.amax(z)

0.9991515931655086

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [13]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [14]:
list = np.random.rand(5)
list

array([0.28792726, 0.14923894, 0.6919523 , 0.2973984 , 0.72473384])

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [15]:
np.sum(list)

2.1512507357124684

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [16]:
l = [x for x in range(11)]
len(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [17]:
np.random.rand(10)

array([0.25114274, 0.6935449 , 0.05556712, 0.57518466, 0.69707606,
       0.96958678, 0.55329755, 0.10642598, 0.82185519, 0.60515357])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [18]:
a = np.random.rand(5)
b = np.random.rand(5)
(a==b).all()

False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [23]:
arrayFloat32 = np.random.random(10).astype(np.float32)
arrayInt32 = arrayFloat32.astype(np.int32)
print(arrayFloat32)
print(arrayInt32)

[0.8128403  0.7599275  0.1795884  0.43116695 0.29434606 0.08907077
 0.32365394 0.11158504 0.9083377  0.31364876]
[0 0 0 0 0 0 0 0 0 0]


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [24]:
arrayRandom = np.random.rand(5,5)
normal = np.linalg.norm(arrayRandom)
normalArray = arrayRandom/normal
print(arrayRandom)
print(normal)
print(normalArray)

[[0.70754506 0.58006113 0.06316498 0.6774394  0.75986477]
 [0.78033724 0.88632081 0.80807754 0.17640886 0.8098844 ]
 [0.62554288 0.91168134 0.6305439  0.95875656 0.84005506]
 [0.12861494 0.90323584 0.16592111 0.15585587 0.11304079]
 [0.34247135 0.15635294 0.21470907 0.92688251 0.18821144]]
3.13627402655461
[[0.22560052 0.18495231 0.02014013 0.21600134 0.24228265]
 [0.24881029 0.28260312 0.25765527 0.05624791 0.25823139]
 [0.19945415 0.29068931 0.20104873 0.30569923 0.26785129]
 [0.04100883 0.28799647 0.05290389 0.0496946  0.03604302]
 [0.10919688 0.04985309 0.06845992 0.2955362  0.06001116]]


#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [21]:
y = np.random.rand(2,2)
y

array([[0.07984154, 0.97744236],
       [0.47220592, 0.49628374]])

In [22]:
np.transpose(y)

array([[0.07984154, 0.47220592],
       [0.97744236, 0.49628374]])

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)